#!/bin/bash

current_dir=$(pwd)
parent_dir=$(dirname "$current_dir")

find "$current_dir" -maxdepth 1 -type f -name "*.html" -newer "$parent_dir" -exec cp -u {} "$parent_dir" \; -exec echo "Copied: {}" \;

